version: '3.7'

services:
  mysql-db:
    image: mysql:8.0
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_finances
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql  
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma
      links:
        - mysql-db
      environment:
        PMA_HOST: mysql-db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8082:80
        
#docker inspect  meu-mysql | grep IPAddress

  